"""add_course_folder

Revision ID: 35fd77e55fea
Revises: 20260708_0001
Create Date: 2026-07-11 13:13:21.740004+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35fd77e55fea'
down_revision: str | None = '20260708_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_folder',
    sa.Column('folder_name', sa.String(length=100), nullable=False, comment='Folder name'),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False, comment='Teacher user ID'),
    sa.Column('org_id', sa.BigInteger(), nullable=True, comment='Organization ID'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Sort order'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), server_default='0', nullable=False, comment='逻辑删除：0-未删除 1-已删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_folder_org_id'), 'course_folder', ['org_id'], unique=False)
    op.create_index(op.f('ix_course_folder_teacher_id'), 'course_folder', ['teacher_id'], unique=False)
    op.alter_column('course', 'status',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_comment='Status: 0-disabled 1-active 2-ended',
               existing_nullable=False)
    op.alter_column('course', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('course', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('course', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('course', 'is_deleted',
               existing_type=mysql.INTEGER(),
               type_=sa.SmallInteger(),
               comment='逻辑删除：0-未删除 1-已删除',
               existing_comment='Is deleted: 0-no 1-yes',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('eval_indicator', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('eval_indicator', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('eval_result', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('eval_result', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('llm_call_log', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('llm_call_log', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('report_record', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('report_record', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_org', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_org', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_role', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_role', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_user', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_user', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('train_achievement', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('train_achievement', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('train_project', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('train_project', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('train_project', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('train_project', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('train_achievement', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('train_achievement', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_user', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_user', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_role', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_role', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_org', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('sys_org', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('report_record', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('report_record', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('llm_call_log', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('llm_call_log', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('eval_result', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('eval_result', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('eval_indicator', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('eval_indicator', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('course', 'is_deleted',
               existing_type=sa.SmallInteger(),
               type_=mysql.INTEGER(),
               comment='Is deleted: 0-no 1-yes',
               existing_comment='逻辑删除：0-未删除 1-已删除',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('course', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('course', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('course', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('course', 'status',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_comment='Status: 0-disabled 1-active 2-ended',
               existing_nullable=False)
    op.drop_index(op.f('ix_course_folder_teacher_id'), table_name='course_folder')
    op.drop_index(op.f('ix_course_folder_org_id'), table_name='course_folder')
    op.drop_table('course_folder')
    # ### end Alembic commands ###
